[package]
name = "sim-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
i18n = { workspace = true }
track-model = { workspace = true }
world-coords = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
