// The forest performance test: writes a throw-away mod with one straight line
// through a wood of a given size, and runs the simulator on it.
//
// A wood is the one piece of scenery whose cost is not bounded by the line —
// a hundred masts is a hundred masts, but "the corridor is forest" is however
// many trees fit in twenty-four square kilometres. The numbers that matter are
// in the simulator's own diagnostics (F6): frame time, entity count, triangles
// and how many tiles are resident. This puts a known number of trees in front
// of the camera so those numbers mean something.
//
// Run:
//   node tools/trees/bench_forest.mjs --trees 20000
//   node tools/trees/bench_forest.mjs --trees 60000 --length 12000 --run
//
// `--run` builds nothing: `cargo build -p app` first, then it starts
// `target/debug/train-sim` with the overlays open and takes a screenshot into
// `screenshots/`. The mod lands in `mods/_forest_bench/`, which is gitignored.

import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const MOD = join(ROOT, 'mods', '_forest_bench');

/** The stands the wood is mixed from, as `mods/trees` tags them. */
const MIXED = [
  'rotbuche', 'rotbuche', 'stieleiche', 'hainbuche', 'bergahorn', 'winterlinde',
  'sandbirke', 'vogelkirsche', 'esche', 'bergulme',
];
const CONIFER = ['fichte', 'fichte', 'fichte', 'kiefer', 'weisstanne', 'douglasie', 'laerche'];
const SCRUB = ['robinie', 'salweide', 'holunder', 'schlehe', 'weissdorn', 'hasel'];

const DEG_LAT = 1 / 111_320;
const DEG_LON = 1 / (111_320 * Math.cos((52 * Math.PI) / 180));
/// How far from the track the terrain reaches (`TerrainOptions::radius`); a
/// tree outside it stands on no tile and is never spawned.
const HALF_WIDTH = 1_000;
/// Nothing inside this of the axis — the strip the terrain pulls up to rail
/// height (`content::terrain::TREE_TRACK_CLEARANCE`).
const CLEARANCE = 60;

function main() {
  const argv = process.argv.slice(2);
  const number = (flag, fallback) => {
    const i = argv.indexOf(flag);
    return i >= 0 ? Number(argv[i + 1]) : fallback;
  };
  const trees = number('--trees', 20_000);
  const length = number('--length', 8_000);
  const run = argv.includes('--run');

  rmSync(MOD, { recursive: true, force: true });
  mkdirSync(join(MOD, 'lines'), { recursive: true });
  writeFileSync(
    join(MOD, 'mod.ron'),
    `// Generated by tools/trees/bench_forest.mjs — a throw-away line for measuring
// what a big wood costs. Not content; delete it whenever.
(
    id: "bench",
    name: "Waldmessung",
    version: "1.0.0",
    author: "Connected Rails",
    description: "Eine gerade Strecke durch einen Wald, zum Messen.",
    depends: ["trees"],
    enabled: true,
)
`,
    'utf8',
  );
  writeFileSync(join(MOD, 'lines', 'wald.ron'), line(trees, length), 'utf8');
  const perTree = ((length * (HALF_WIDTH - CLEARANCE) * 2) / trees).toFixed(0);
  console.log(
    `mods/_forest_bench: ${trees} trees over ${length / 1000} km, ` +
      `one per ${perTree} m² of the ${(HALF_WIDTH * 2) / 1000} km wide corridor`,
  );

  if (!run) {
    console.log('\nRun it with:\n  cargo build -p app\n  ' +
      `./target/debug/train-sim --line bench:wald --overlays --frames 600 ` +
      `--screenshot screenshots/forest-bench-${trees}.png`);
    return;
  }
  const shot = `screenshots/forest-bench-${trees}.png`;
  console.log(`\nrunning… (${shot})`);
  execFileSync(
    join(ROOT, 'target', 'debug', 'train-sim'),
    ['--line', 'bench:wald', '--overlays', '--frames', '600', '--screenshot', shot],
    { cwd: ROOT, stdio: ['ignore', 'ignore', 'inherit'] },
  );
  console.log(`done — read ${shot} and note the DIAGNOSTICS block`);
}

/** A straight line east from 52°/10° with a wood over the whole corridor. */
function line(count, length) {
  // Deterministic, so two runs measure the same wood.
  let state = 0x9e3779b9;
  const rnd = () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 4294967296;
  };
  const species = [];
  for (const [members, share] of [[MIXED, 0.5], [CONIFER, 0.35], [SCRUB, 0.15]]) {
    for (const member of members) {
      for (const variant of ['a', 'b', 'c']) {
        for (let k = 0; k < Math.round(share * 20); k++) species.push(`trees:${member}_${variant}`);
      }
    }
  }

  const rows = [];
  for (let i = 0; i < count; i++) {
    const along = rnd() * length;
    const side = rnd() < 0.5 ? -1 : 1;
    const across = side * (CLEARANCE + rnd() * (HALF_WIDTH - CLEARANCE));
    rows.push(
      `        (object: "${species[Math.floor(rnd() * species.length)]}", ` +
        `lat: ${(52 + across * DEG_LAT).toFixed(6)}, ` +
        `lon: ${(10 + along * DEG_LON).toFixed(6)}, ` +
        `yaw_deg: ${(rnd() * 360).toFixed(1)}, scale: ${(0.7 + rnd() * 0.6).toFixed(2)}),`,
    );
  }

  return `// Generated by tools/trees/bench_forest.mjs — ${count} trees over ${length} m.
(
    name: "Waldmessung",
    geoid_offset: 46.0,
    electrification: "ac-15kv",
    nodes: [Buffer, Buffer],
    edges: [
        (
            from: 0,
            to: 1,
            start: Geo(point: (lat: 52.0, lon: 10.0, height: 100.0), heading_deg: 90.0),
            segments: [(len: ${length}.0, k0: 0.0, dk: 0.0)],
            speed: [(0.0, 160.0)],
            electrification: [(0.0, "ac-15kv")],
        ),
    ],
    sections: [(edges: [0])],
    trees: [
${rows.join('\n')}
    ],
)
`;
}

main();
