#!/usr/bin/env python3
"""Builds the `people` mod out of the roster: export, post-process, register.

Runs ``mh2_export.py`` for the roster (or the characters named with ``--only``),
then ``build_character.py`` for every raw export, and writes the
``characters/<id>.ron`` entry the mod runtime reads. The raw exports stay in a
cache directory outside the repository; only the finished glTF and its RON land
in ``mods/people/``.

Usage::

    ~/.local/share/makehuman2/venv/bin/python tools/characters/build_all.py
    ~/.local/share/makehuman2/venv/bin/python tools/characters/build_all.py --only f03_lena
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
MOD = REPO / "mods" / "people"

GENDER = {"male": "Male", "female": "Female"}
ROLE = {"player": "Player", "passenger": "Passenger"}


def ron_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def character_ron(meta: dict, stats: dict) -> str:
    """The `characters/<id>.ron` entry — see `content::characters::CharacterSpec`."""
    roles = ", ".join(ROLE[r] for r in meta.get("roles", ["passenger"]))
    tags = ", ".join(ron_string(t) for t in meta.get("tags", []))
    lods = " / ".join(str(level["tris"]) for level in stats.get("lods", []))
    return (
        f"// Generated by tools/characters/build_all.py out of roster.json — edit the roster,\n"
        f"// not this file. {lods} triangles per level of detail.\n"
        f"(\n"
        f"    name: {ron_string(meta['name'])},\n"
        f"    model: {ron_string(f'people/assets/{meta['id']}.glb')},\n"
        f"    gender: {GENDER.get(meta.get('gender', ''), 'Unspecified')},\n"
        f"    roles: [{roles}],\n"
        f"    height: {stats.get('height_m', meta.get('height_m', 0.0)):.2f},\n"
        f"    tags: [{tags}],\n"
        f")\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--roster", type=Path, default=HERE / "roster.json")
    parser.add_argument("--only", type=str, default="", help="comma-separated character ids")
    parser.add_argument("--raw", type=Path, default=Path.home() / ".cache/connected-rails/characters/raw",
                        help="where the raw MakeHuman exports are kept")
    parser.add_argument("--skip-export", action="store_true", help="reuse the raw exports in --raw")
    parser.add_argument("--body-atlas", default="2048x1024")
    parser.add_argument("--cutout-atlas", default="1024x512")
    parser.add_argument("--lods", default="30000,6000,1600,500")
    args = parser.parse_args()

    roster = json.loads(args.roster.read_text(encoding="utf-8"))
    ids = [c["id"] for c in roster["characters"]]
    if args.only:
        wanted = args.only.split(",")
        unknown = [w for w in wanted if w not in ids]
        if unknown:
            print(f"unknown character ids: {unknown}", file=sys.stderr)
            return 2
        ids = wanted

    python = sys.executable
    if not args.skip_export:
        command = [python, str(HERE / "mh2_export.py"), "--roster", str(args.roster), "--out", str(args.raw)]
        if args.only:
            command += ["--only", args.only]
        print("+", " ".join(command))
        if subprocess.run(command, check=False).returncode != 0:
            print("export failed", file=sys.stderr)
            return 1

    (MOD / "assets").mkdir(parents=True, exist_ok=True)
    (MOD / "characters").mkdir(parents=True, exist_ok=True)
    failures = 0
    total_bytes = 0
    for id_ in ids:
        raw = args.raw / f"{id_}.glb"
        meta_path = args.raw / f"{id_}.meta.json"
        if not raw.exists() or not meta_path.exists():
            print(f"{id_}: no raw export", file=sys.stderr)
            failures += 1
            continue
        out = MOD / "assets" / f"{id_}.glb"
        stats_path = args.raw / f"{id_}.stats.json"
        command = [python, str(HERE / "build_character.py"), str(raw), str(out),
                   "--meta", str(meta_path), "--stats", str(stats_path),
                   "--body-atlas", args.body_atlas, "--cutout-atlas", args.cutout_atlas,
                   "--lods", args.lods, "--check"]
        if subprocess.run(command, check=False).returncode != 0:
            print(f"{id_}: build failed", file=sys.stderr)
            failures += 1
            continue
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        stats = json.loads(stats_path.read_text(encoding="utf-8"))
        (MOD / "characters" / f"{id_}.ron").write_text(character_ron(meta, stats), encoding="utf-8")
        size = out.stat().st_size
        total_bytes += size
        print(f"{id_}: {size // 1024} KB")
    print(f"{len(ids) - failures} of {len(ids)} characters built, {total_bytes // 1024} KB in mods/people/assets")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
