-- Generated by tools/gen_form_signals.py — edit the generator.
-- Every demo signal advances synchronously at t = 10, 20, 30 … seconds.
local M = {}
local STEP = 10.0

local function phase(ctx, count)
  return math.floor((ctx.time + 0.000001) / STEP) % count
end

function M.aspect(ctx)
  if ctx.main == "stop" then
    if phase(ctx, 2) == 0 then
      return { main = "stop", lamps = { "lamp_red" } }
    end
    return { main = "proceed", lamps = { "fluegel1", "lamp_green" } }
  end

  if ctx.main == "proceed_slow" then
    local p = phase(ctx, 3)
    if p == 0 then
      return { main = "stop", lamps = { "lamp_red" } }
    elseif p == 1 then
      return { main = "proceed", lamps = { "fluegel1", "lamp_green" } }
    end
    return { main = "proceed_slow", speed = 40.0,
             lamps = { "fluegel1", "fluegel2", "lamp_green", "lamp_yellow" } }
  end

  -- A mechanically coupled two-arm signal has only Hp 0 and Hp 2. One
  -- channel drives both blades and spectacles, so an intermediate Hp 1
  -- command cannot create a contradictory blade position.
  if ctx.main == "proceed" then
    if phase(ctx, 2) == 0 then
      return { main = "stop", lamps = { "lamp_red" } }
    end
    return { main = "proceed_slow", speed = 40.0,
             lamps = { "fluegel_gekuppelt", "lamp_green", "lamp_yellow" } }
  end

  if ctx.distant == "expect_stop" then
    if phase(ctx, 2) == 0 then
      return { distant = "expect_stop", lamps = { "vr0_licht" } }
    end
    return { distant = "expect_proceed",
             lamps = { "scheibe_weg", "vr1_licht",
                       "vr_blende_links_gruen", "vr_blende_rechts_gruen" } }
  end

  if ctx.distant == "expect_slow" then
    local p = phase(ctx, 3)
    if p == 0 then
      return { distant = "expect_stop", lamps = { "vr0_licht" } }
    elseif p == 1 then
      return { distant = "expect_proceed",
               lamps = { "scheibe_weg", "vr1_licht",
                         "vr_blende_links_gruen", "vr_blende_rechts_gruen" } }
    end
    return { distant = "expect_slow",
             lamps = { "vr2_fluegel", "vr2_licht",
                       "vr_blende_rechts_gruen" } }
  end

  if ctx.shunt == "stop" then
    if phase(ctx, 2) == 0 then
      return { shunt = "stop", lamps = { "sh_white" } }
    end
    return { shunt = "proceed",
             lamps = { "sperrscheibe_frei", "sh_white" } }
  end

  return nil
end

return M
