#!/usr/bin/env node
// Turns the catalogue into the `wind` mod: one glTF per class and variant,
// four levels of detail each, the moving parts as named nodes, plus the
// `objects/*.ron` a line places and the manifest.
//
//   wind.json ──build_wind.mjs──▶ mods/wind/assets/<class>_<variant>.gltf
//             │     (lib/kit)                      + <class>.bin
//             └─────────────────▶ mods/wind/objects/<class>_<variant>.ron
//                                 mods/wind/mod.ron
//
// Node 20 or newer and nothing else, like the masts — the glTF writer, the
// geometry primitives, the concrete and zinc painters and the rasteriser are
// `tools/pylons/lib`'s, and the coating is painted here (`lib/texture.mjs`).
//
//   node tools/wind/build_wind.mjs
//   node tools/wind/build_wind.mjs --only wea-80
//   node tools/wind/build_wind.mjs --check      # every face outward, every map there? writes nothing
//   node tools/wind/build_wind.mjs --report     # triangle budget, writes nothing
//   node tools/wind/build_wind.mjs --preview    # picture sheets into /tmp/wind-preview

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { encodePng } from '../trees/lib/png.mjs';
import { triangleCount } from '../pylons/lib/geom.mjs';
import { BufferBuilder, writeBuffer, writeGltfScene } from '../pylons/lib/gltf.mjs';
import { METRES_PER_PIXEL_PER_METRE } from '../pylons/lib/preview.mjs';
import {
  COATING,
  CONCRETE,
  DARK,
  GALVANISED,
  LAMP,
  TILT_DEG,
  buildTurbine,
  chordAt,
  windingAgrees,
} from './lib/kit.mjs';
import { renderHandovers, renderSheet } from './lib/preview.mjs';
import { paint } from './lib/texture.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const modDir = join(repo, 'mods', 'wind');
const assetDir = join(modDir, 'assets');
const objectDir = join(modDir, 'objects');

const COPYRIGHT = 'Connected Rails, EUPL v. 1.2 — generated by tools/wind/build_wind.mjs';
const GENERATOR = 'tools/wind/build_wind.mjs (Connected Rails)';

/** One millimetre a texel over a metre — the masts' size, and their frequency budget. */
const TEXTURE_SIZE = 1024;

/** The furthest a turbine is drawn [m]. */
const CULL = 8000;

const VARIANT_LABEL = {
  standard: 'Kastengondel',
  enercon: 'Enercon',
  gitter: 'Gittermast',
};

/**
 * The materials, in the order `lib/kit.mjs` indexes them.
 *
 * The coating, the concrete and the zinc all come out of painted maps, so
 * their factors are one — a factor multiplies its texture, and anything but
 * one would be a second opinion about a number the map already has.
 *
 * The lamp is Feuer W, rot: a red the eye reads as a signal, and an emissive
 * strength that survives the physical exposure of a dusk sky — the same order
 * of magnitude the signal lenses use, because it is seen from the same train.
 */
function materialsOf(maps) {
  const white = [1, 1, 1, 1];
  return [
    { name: 'lack', color: white, metallic: 1, roughness: 1, normalScale: 0.5, maps: maps.coating },
    { name: 'fundament', color: white, metallic: 1, roughness: 1, normalScale: 1.0, maps: maps['spun-concrete'] },
    { name: 'verzinkt', color: white, metallic: 1, roughness: 1, normalScale: 0.36, maps: maps['steel-lattice'] },
    {
      name: 'hindernisfeuer',
      color: [0.8, 0.03, 0.03, 1],
      metallic: 0,
      roughness: 0.3,
      emissive: [1.0, 0.04, 0.02],
      emissiveStrength: 40,
    },
    { name: 'dunkel', color: [0.05, 0.05, 0.055, 1], metallic: 0, roughness: 0.7 },
  ];
}

/**
 * Paints the tiling maps of every material and writes them beside the models,
 * once. Returns the image list and, per material, where its maps sit in it.
 */
function paintTextures(write) {
  const images = [];
  const maps = {};
  for (const kind of ['coating', 'spun-concrete', 'steel-lattice']) {
    const painted = paint(kind, TEXTURE_SIZE);
    const slots = {};
    for (const map of ['colour', 'orm', 'normal']) {
      const file = `${painted.id}_${map}.png`;
      slots[map] = images.length;
      images.push(file);
      if (write) {
        writeFileSync(join(assetDir, file), encodePng(painted[map], TEXTURE_SIZE, TEXTURE_SIZE));
      }
    }
    maps[kind] = slots;
  }
  return { images, maps };
}

const stem = (id) => id.replaceAll('-', '_');

/**
 * Where the levels hand over [m], for one class.
 *
 * What stops resolving first on a turbine is the **blade**: a section is a
 * line once its chord is a couple of pixels, and past that a level with an
 * aerofoil in it is triangles for nothing. So the bands come off the outer
 * chord — the masts' rule, applied to the member a turbine actually has:
 *
 * - **LOD0 → LOD1** where the outer chord is three pixels — the section's
 *   shape has gone, only its width is left.
 * - **LOD1 → LOD2** where it is a pixel and a quarter — now it is a line.
 * - **LOD2 → LOD3** where the tower's foot is under two pixels: there is no
 *   room for a taper, and a stick with a diamond on it is the honest picture.
 * - **Culled** at eight kilometres — a 200 m machine is still forty pixels
 *   tall there and its lamp is what a night landscape *is*; in practice the
 *   terrain under it decides, because a tile that is not built carries no
 *   turbine.
 *
 * The reference is the masts': 1440 lines at 45° vertical field of view.
 */
function lodDistances(spec) {
  const perPixel = (metres, pixels) => metres / (pixels * METRES_PER_PIXEL_PER_METRE);
  const chord = chordAt(spec.blade, 0.8);
  const bands = [
    perPixel(chord, 3.0),
    perPixel(chord, 1.25),
    perPixel(spec.tower_base_m, 2.0),
    CULL,
  ];
  let previous = 0;
  return bands.map((d) => {
    const clamped = Math.min(Math.max(d, previous + 1), CULL);
    previous = clamped;
    return Math.round(clamped);
  });
}

function ron(spec, variant) {
  const name = `${spec.name_de} (${VARIANT_LABEL[variant]})`;
  const file = `${stem(spec.id)}_${variant}`;
  const tags = [...spec.tags, variant];
  const lod = lodDistances(spec);
  return {
    file,
    text: `// ${name}, hub ${spec.hub_m} m, rotor ${spec.rotor_m} m — generated by
// tools/wind/build_wind.mjs; edit wind.json, not this file.
(
    name: "${name}",
    model: "wind/assets/${file}.gltf",
    lateral_offset: 0.0,
    yaw_deg: 0.0,
    height: 0.0,
    lod_distances: [${lod.join(', ')}],
    tags: [${tags.map((t) => `"${t}"`).join(', ')}],
)
`,
  };
}

/** The tilt of the rotor axis as a glTF quaternion about X. */
function tiltQuaternion() {
  const half = (TILT_DEG * Math.PI) / 360;
  return [Math.sin(half), 0, 0, Math.cos(half)];
}

/**
 * The node tree of one variant. The levels are mesh nodes named `_LOD<n>`;
 * `nacelle` and `rotor` are the two nodes the game moves, and everything
 * that moves with them hangs under them.
 */
function nodesOf(spec, variant, buffer) {
  const roots = [];
  const nacelleChildren = [];
  const rotorChildren = [];
  const lampChildren = [];
  const tris = [];
  for (let detail = 0; detail < 4; detail++) {
    const built = buildTurbine(spec, { variant, detail });
    const parts = (pairs) =>
      pairs.filter(([g]) => g.positions.length).map(([g, material]) => ({ packed: buffer.add(g), material }));
    roots.push({
      name: `turm_LOD${detail}`,
      parts: parts([
        [built.tower.coating, COATING],
        [built.tower.steel, GALVANISED],
        [built.tower.concrete, CONCRETE],
      ]),
    });
    nacelleChildren.push({
      name: `gondel_LOD${detail}`,
      parts: parts([
        [built.nacelle.coating, COATING],
        [built.nacelle.dark, DARK],
      ]),
    });
    if (built.lamps.positions.length) {
      lampChildren.push({ name: `lampe_LOD${detail}`, parts: parts([[built.lamps, LAMP]]) });
    }
    rotorChildren.push({ name: `rotor_LOD${detail}`, parts: parts([[built.rotor, COATING]]) });
    tris.push(
      [built.tower.coating, built.tower.steel, built.tower.concrete, built.nacelle.coating, built.nacelle.dark, built.lamps, built.rotor]
        .map(triangleCount)
        .reduce((a, b) => a + b, 0),
    );
  }
  if (lampChildren.length) {
    // The lamps are night furniture (`_NIGHT`, off by day) and blink under
    // that: `blink` is what `world_render::wind` switches on the clock.
    nacelleChildren.push({
      name: 'feuer_NIGHT',
      children: [{ name: 'blink', children: lampChildren }],
    });
  }
  nacelleChildren.push({
    name: 'rotor',
    translation: [0, 0, -spec.overhang_m],
    rotation: tiltQuaternion(),
    extras: { rotor_diameter: spec.rotor_m, rated_rpm: spec.rated_rpm, hub_height: spec.hub_m },
    children: rotorChildren,
  });
  roots.push({
    name: 'nacelle',
    translation: [0, spec.hub_m, 0],
    children: nacelleChildren,
  });
  return { roots, tris };
}

function build(classes, { write, report }) {
  const { images, maps } = paintTextures(write);
  const rows = [];
  for (const spec of classes) {
    const buffer = new BufferBuilder();
    const files = [];
    for (const variant of spec.variants) {
      const { roots, tris } = nodesOf(spec, variant, buffer);
      const entry = ron(spec, variant);
      files.push({ roots, entry });
      rows.push({ file: entry.file, tris, tip: spec.hub_m + spec.rotor_m / 2 });
    }
    if (!write) continue;
    const bin = `${stem(spec.id)}.bin`;
    writeBuffer(assetDir, bin, buffer.toBuffer());
    for (const { roots, entry } of files) {
      writeGltfScene({
        path: join(assetDir, `${entry.file}.gltf`),
        name: entry.file,
        buffer: bin,
        bufferLength: buffer.length,
        roots,
        materials: materialsOf(maps),
        images,
        copyright: COPYRIGHT,
        generator: GENERATOR,
      });
      writeFileSync(join(objectDir, `${entry.file}.ron`), entry.text, 'utf8');
    }
  }
  if (report || write) {
    let total = 0;
    for (const r of rows) {
      total += r.tris[0];
      console.log(
        `${r.file.padEnd(22)} tip ${r.tip.toFixed(0).padStart(3)} m  ` +
          r.tris.map((t) => String(t).padStart(6)).join(' '),
      );
    }
    console.log(`${rows.length} variants, ${total} triangles at LOD0`);
  }
  return rows;
}

/** Every face outward, at every level of every variant. */
function check(classes) {
  let bad = 0;
  for (const spec of classes) {
    for (const variant of spec.variants) {
      for (let detail = 0; detail < 4; detail++) {
        const built = buildTurbine(spec, { variant, detail });
        const parts = {
          tower: built.tower.coating,
          steel: built.tower.steel,
          concrete: built.tower.concrete,
          nacelle: built.nacelle.coating,
          dark: built.nacelle.dark,
          lamps: built.lamps,
          rotor: built.rotor,
        };
        for (const [what, geometry] of Object.entries(parts)) {
          if (!geometry.positions.length) continue;
          // Winding against the normals is what back-face culling shows as a
          // hole; the masts' centre-of-piece test cannot judge a coned blade.
          const { against, agree } = windingAgrees(geometry);
          if (against) {
            bad += against;
            console.error(
              `${spec.id}_${variant} LOD${detail} ${what}: ${against} of ${against + agree} triangles wound against their normals`,
            );
          }
        }
      }
    }
  }
  return bad;
}

/** Audit the shipped glTF and PNG files, not only their inputs. */
function checkGenerated(classes) {
  let bad = 0;
  const seen = new Set();
  for (const spec of classes) {
    for (const variant of spec.variants) {
      const file = `${stem(spec.id)}_${variant}`;
      const path = join(assetDir, `${file}.gltf`);
      if (!existsSync(path)) {
        console.error(`${file}: generated glTF is missing`);
        bad++;
        continue;
      }
      const gltf = JSON.parse(readFileSync(path, 'utf8'));
      const names = new Set(gltf.nodes.map((n) => n.name));
      for (const wanted of ['nacelle', 'rotor', 'turm_LOD0', 'gondel_LOD0', 'rotor_LOD3']) {
        if (!names.has(wanted)) {
          console.error(`${file}: node ${wanted} is missing`);
          bad++;
        }
      }
      const rotor = gltf.nodes.find((n) => n.name === 'rotor');
      if (!rotor?.extras?.rotor_diameter || !rotor?.extras?.rated_rpm || !rotor?.extras?.hub_height) {
        console.error(`${file}: the rotor node carries no diameter, speed and hub height`);
        bad++;
      }
      if (spec.marking !== names.has('blink')) {
        console.error(`${file}: marking is ${spec.marking} but the lamps are ${names.has('blink')}`);
        bad++;
      }
      for (const image of gltf.images ?? []) {
        if (seen.has(image.uri)) continue;
        seen.add(image.uri);
        const imagePath = join(assetDir, image.uri);
        if (!existsSync(imagePath)) {
          console.error(`${file}: missing map ${image.uri}`);
          bad++;
          continue;
        }
        const png = readFileSync(imagePath);
        const width = png.length >= 24 ? png.readUInt32BE(16) : 0;
        if (width !== TEXTURE_SIZE) {
          console.error(`${image.uri}: ${width} px, expected ${TEXTURE_SIZE}`);
          bad++;
        }
      }
    }
  }
  return { bad, images: seen.size };
}

function manifest(count) {
  return `// Generated by tools/wind/build_wind.mjs — see tools/wind/README.md.
(
    id: "wind",
    name: "Windenergieanlagen",
    version: "1.0.0",
    author: "Connected Rails",
    description: "Die Windräder der deutschen Landschaft: vier Generationen vom 600-kW-Rad der Neunziger bis zur 5-MW-Anlage, als Kastengondel, als Enercon und auf dem Gittermast — ${count} Varianten, parametrisch aus dem Katalog erzeugt. Gondel und Rotor sind bewegliche Knoten; das Spiel dreht sie nach dem Wetter.",
    depends: [],
    enabled: true,
)
`;
}

function main() {
  const args = process.argv.slice(2);
  const only = args.find((a) => a.startsWith('--only='))?.slice(7)
    ?? (args.includes('--only') ? args[args.indexOf('--only') + 1] : null);
  const atlas = JSON.parse(readFileSync(join(here, 'wind.json'), 'utf8'));
  let classes = atlas.classes;
  if (only) {
    const wanted = new Set(only.split(',').map((s) => s.trim()));
    classes = classes.filter((c) => wanted.has(c.id));
    const missing = [...wanted].filter((w) => !atlas.classes.some((c) => c.id === w));
    if (missing.length) {
      console.error(`no such class: ${missing.join(', ')}`);
      process.exit(1);
    }
  }

  if (args.includes('--check')) {
    const bad = check(classes);
    if (bad) {
      console.error(`${bad} inward-facing triangles`);
      process.exit(1);
    }
    const generated = checkGenerated(classes);
    if (generated.bad) {
      console.error(`${generated.bad} generated asset errors`);
      process.exit(1);
    }
    console.log(
      `all ${classes.length} classes face outward at every level; ` +
        `every node the game moves is there and ${generated.images} maps are ${TEXTURE_SIZE}px`,
    );
    return;
  }
  if (args.includes('--preview')) {
    const out = renderSheet(classes, '/tmp/wind-preview');
    renderHandovers(classes, '/tmp/wind-preview', lodDistances, METRES_PER_PIXEL_PER_METRE);
    console.log(`${out} sheets and ${classes.length} hand-over sheets in /tmp/wind-preview`);
    return;
  }
  if (args.includes('--report')) {
    build(classes, { write: false, report: true });
    for (const spec of classes) console.log(`${spec.id}: LOD bands ${lodDistances(spec).join(' / ')} m`);
    return;
  }

  mkdirSync(assetDir, { recursive: true });
  mkdirSync(objectDir, { recursive: true });
  if (!only) {
    for (const dir of [assetDir, objectDir]) {
      for (const f of readdirSync(dir)) rmSync(join(dir, f));
    }
  }
  const rows = build(classes, { write: true, report: false });
  if (!only) writeFileSync(join(modDir, 'mod.ron'), manifest(rows.length), 'utf8');
}

main();
