#!/usr/bin/env node
// Turns the atlas into the `pylons` mod: one glTF per mast variant, four levels
// of detail each, plus the `objects/*.ron` a route places and the manifest.
//
//   pylons.json ──build_pylons.mjs──▶ mods/pylons/assets/<type>_<role>.gltf
//               │      (lib/kit)                       + <type>.bin
//               └──────────────────▶ mods/pylons/objects/<type>_<role>.ron
//                                    mods/pylons/mod.ron
//
// Node 20 or newer and nothing else — no npm dependency, no image library, no
// modelling tool. Every triangle in `mods/pylons/` comes out of `lib/kit.mjs`
// and the numbers in `pylons.json`, which is the point: a mast whose crossarm
// is 40 cm too short is a one-line edit to the catalogue and a re-run, not an
// afternoon in Blender.
//
//   node tools/pylons/build_pylons.mjs
//   node tools/pylons/build_pylons.mjs --only donaumast-380,bahnstrommast-110
//   node tools/pylons/build_pylons.mjs --report     # triangle budget, writes nothing
//   node tools/pylons/build_pylons.mjs --preview    # a picture sheet into /tmp
//   node tools/pylons/build_pylons.mjs --ink        # what each level does to the mast's ink

import { mkdirSync, readFileSync, writeFileSync, readdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { encodePng } from '../trees/lib/png.mjs';
import { MEMBER_SCALE, bodyMember, buildMast, finestMember } from './lib/kit.mjs';
import { paint } from './lib/texture.mjs';
import { facing, triangleCount } from './lib/geom.mjs';
import { BufferBuilder, writeGltf, writeBuffer } from './lib/gltf.mjs';
import { inkReport, renderHandovers, renderSheet } from './lib/preview.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const modDir = join(repo, 'mods', 'pylons');
const assetDir = join(modDir, 'assets');
const objectDir = join(modDir, 'objects');

const COPYRIGHT = 'Connected Rails, EUPL v. 1.2 — generated by tools/pylons/build_pylons.mjs';

/**
 * How big the painted maps are.
 *
 * 512 px over a metre is **two millimetres a texel**, and it is the number the
 * painters' frequency budget is cut for: nothing they draw goes above a quarter
 * of it in cycles per metre (`lib/texture.mjs`). At the 256 it started on, the
 * concrete's finest term was half a texel wide and came out as aliasing rather
 * than as sand. Nine PNGs, about three megabytes for the whole catalogue.
 */
const TEXTURE_SIZE = 512;

/**
 * What the steel, the concrete and the wood look like.
 *
 * The base colour, the roughness and the metallic all come out of the painted
 * maps (`lib/texture.mjs`), so the factors here are **one**: in glTF a factor
 * multiplies its texture, and anything but one would be a second opinion about
 * a number the map already has. What is left for the material to say is that
 * this is metal and that is not.
 */
const MATERIALS = {
  'steel-lattice': { name: 'verzinkt', structure: 'steel-lattice', normalScale: 1.0 },
  'steel-tube': { name: 'stahlrohr', structure: 'steel-tube', normalScale: 0.6 },
  'spun-concrete': { name: 'schleuderbeton', structure: 'spun-concrete', normalScale: 1.0 },
  wood: { name: 'holz', structure: 'wood', normalScale: 1.0 },
};

/**
 * The fittings, which stay constants.
 *
 * An insulator is glazed porcelain: smooth, so there is no microstructure worth
 * a roughness map, and small, so there is no room for one to show. A cap-and-pin
 * string is the brown of a fired glaze; the double-bell porcelain of a telegraph
 * pole is white, which is how you can pick a telegraph pole out of a hedge at
 * two hundred metres.
 *
 * **`baseColorFactor` is linear, and that is what went wrong here.** The brown
 * was written as if it were sRGB — 0.40, 0.30, 0.24 is linear 0.40, which is
 * sRGB 168, a milky cream — and under the sky's image-based light at a
 * roughness of 0.24 the strings came out pale pink. Fired brown glaze is
 * sRGB 94, 58, 44, which is the linear triple below; the gloss is down as well,
 * because a string that has hung in the weather for thirty years is glazed, not
 * polished.
 */
const FITTING_MATERIAL = {
  suspension: { name: 'isolator', color: [0.111, 0.043, 0.026, 1], metallic: 0, roughness: 0.32 },
  pin: { name: 'isolator', color: [0.120, 0.048, 0.029, 1], metallic: 0, roughness: 0.30 },
  bell: { name: 'porzellan', color: [0.72, 0.70, 0.65, 1], metallic: 0, roughness: 0.22 },
};

/**
 * The variants of one type: which roles the atlas says it is built in.
 *
 * Height is *not* a variant. The atlas gives a band, the placement gives a
 * scale, and a mast scaled by a tenth either way is the same drawing built
 * taller — which is what a manufacturer does too. Two files per type instead of
 * eight, and a line of Donaumasten still varies along its length.
 */
function variantsOf(type) {
  const roles = type.roles ?? [];
  const out = [];
  if (roles.includes('suspension')) out.push({ role: 'suspension', suffix: 'trag', label: 'Tragmast' });
  if (roles.includes('tension')) out.push({ role: 'tension', suffix: 'abspann', label: 'Abspannmast' });
  if (out.length === 0) out.push({ role: 'suspension', suffix: '', label: '' });
  return out;
}

const stem = (id) => id.replaceAll('-', '_');

/**
 * One pixel, in metres, per metre of distance.
 *
 * The reference the bands are cut for is **1440 lines at the simulator's 45°
 * vertical field of view** — `2 * tan(fov / 2) / lines`. A finer screen resolves
 * a member further out and gets a slightly conservative hand-over; a coarser one
 * a slightly late. That is the same assumption `tools/trees` makes, and it is
 * worth stating rather than hiding: judge a level at the resolution it will be
 * played at, or it will be judged wrong.
 */
const METRES_PER_PIXEL_PER_METRE = (2 * Math.tan(Math.PI / 8)) / 1440;

/**
 * Where the levels hand over [m], for one type.
 *
 * **The mast's height is the wrong thing to scale by**, which is what the first
 * cut of this did. What decides whether a level is still worth its triangles is
 * not how tall the mast is but how thin its *members* are: a 12 m concrete pole
 * with a 9 cm crossarm and a 60 m Donaumast with a 16 cm brace resolve at almost
 * the same distance, and a rule in units of the height puts them a factor of
 * five apart. So the bands come off the geometry:
 *
 * - **LOD0 → LOD1** where the thinnest member drops below a pixel. Past that it
 *   is not drawn, it is *sampled* — some pixel centres hit, others missed, and
 *   the pattern crawls as the camera moves. That is the same failure the
 *   conductors have, and the mast cannot be fixed the same way: a lattice is
 *   three hundred members going in every direction, not one line.
 * - **LOD1 → LOD2** where half the panels, drawn a fifth thicker, have gone the
 *   same way — about two and a half times further out.
 * - **LOD2 → LOD3** where the mast's **body** is under two pixels wide. That is
 *   the honest end of the lattice: below two pixels there is no room for two
 *   legs and a gap between them, so there is nothing inside the outline left to
 *   draw and the bracing finally goes. A pole has nothing inside it to begin
 *   with, so it hands over where its own shaft stops resolving instead.
 * - **Culled** where the whole mast is ten pixels tall. On a 380 kV Donaumast
 *   that is ten kilometres, so the cap decides instead: four kilometres, which
 *   is past where the terrain under it is still built. A 7.5 m telegraph pole
 *   goes at 1.3 km, where it is a tenth of a pixel wide.
 */
function lodDistances(type, height) {
  const perPixel = (metres, pixels) => metres / (pixels * METRES_PER_PIXEL_PER_METRE);
  const finest = finestMember(type);
  const cull = Math.min(4000, Math.max(700, perPixel(height, 10)));
  const lattice = type.build.kind === 'lattice' || type.build.kind === 'portal';
  const bands = [
    perPixel(finest, 1.0),
    perPixel(finest * MEMBER_SCALE[1], 0.55),
    lattice
      ? perPixel(type.build.shaft_m, 2.0)
      : perPixel(bodyMember(type) * MEMBER_SCALE[2], 0.6),
    cull,
  ];
  // Monotone and inside the cull, whatever the proportions of an odd type do.
  let previous = 0;
  return bands.map((d) => {
    const clamped = Math.min(Math.max(d, previous + 1), cull);
    previous = clamped;
    return Math.round(clamped);
  });
}

function ron(type, variant, height) {
  const name = variant.label ? `${type.name_de} (${variant.label})` : type.name_de;
  const file = variant.suffix ? `${stem(type.id)}_${variant.suffix}` : stem(type.id);
  const tags = [...type.tags];
  if (variant.suffix) tags.push(variant.suffix);
  const lod = lodDistances(type, height);
  return {
    file,
    text: `// ${name}, ${height.toFixed(0)} m — generated by tools/pylons/build_pylons.mjs;
// edit pylons.json, not this file.
(
    name: "${name}",
    model: "pylons/assets/${file}.gltf",
    lateral_offset: 0.0,
    yaw_deg: 0.0,
    height: 0.0,
    lod_distances: [${lod.join(', ')}],
    tags: [${tags.map((t) => `"${t}"`).join(', ')}],
)
`,
  };
}

/**
 * Paints the three maps of every material an atlas uses and writes them beside
 * the models, once — the whole catalogue shares them, so a line of Donaumasten
 * and the concrete pole beside it are nine PNGs between them.
 *
 * Returns the image list and, per material, where its maps sit in it.
 */
function paintTextures(types, write) {
  const kinds = [...new Set(types.map((t) => t.structure))];
  // The foundations are concrete whatever the mast is made of.
  if (types.some((t) => t.build.kind === 'lattice' || t.build.kind === 'portal')) {
    if (!kinds.includes('spun-concrete')) kinds.push('spun-concrete');
  }
  const images = [];
  const maps = {};
  // Keyed on the painter's own id, not on the structure: a steel tube and a
  // steel lattice are the same zinc, and painting it twice would ship the same
  // three files under two names.
  const byId = new Map();
  for (const kind of kinds) {
    const painted = paint(kind, TEXTURE_SIZE);
    if (!byId.has(painted.id)) {
      const slots = {};
      for (const map of ['colour', 'orm', 'normal']) {
        const file = `${painted.id}_${map}.png`;
        slots[map] = images.length;
        images.push(file);
        if (write) {
          writeFileSync(join(assetDir, file), encodePng(painted[map], TEXTURE_SIZE, TEXTURE_SIZE));
        }
      }
      byId.set(painted.id, slots);
    }
    maps[kind] = byId.get(painted.id);
  }
  return { images, maps };
}

/** The three materials of one type, in the order the parts index them. */
function materialsOf(type, maps) {
  const structure = MATERIALS[type.structure];
  const white = [1, 1, 1, 1];
  return [
    {
      name: structure.name,
      color: white,
      // One, because the map has the number. A factor here would be a second
      // opinion about it.
      metallic: 1,
      roughness: 1,
      normalScale: structure.normalScale,
      maps: maps[type.structure],
    },
    FITTING_MATERIAL[type.build.fitting] ?? FITTING_MATERIAL.suspension,
    {
      name: 'fundament',
      color: white,
      metallic: 1,
      roughness: 1,
      normalScale: 1.0,
      maps: maps['spun-concrete'],
    },
  ];
}

function build(types, { write, report }) {
  const { images, maps } = paintTextures(types, write);
  const rows = [];
  for (const type of types) {
    const height = (type.height_m[0] + type.height_m[1]) / 2;
    const buffer = new BufferBuilder();
    const files = [];

    for (const variant of variantsOf(type)) {
      const levels = [];
      for (let detail = 0; detail < 4; detail++) {
        const { structure, fittings, concrete } = buildMast(type, {
          role: variant.role,
          height,
          detail,
        });
        const parts = [{ packed: buffer.add(structure), material: 0 }];
        if (fittings.positions.length) parts.push({ packed: buffer.add(fittings), material: 1 });
        if (concrete.positions.length) parts.push({ packed: buffer.add(concrete), material: 2 });
        levels.push({
          name: `mast_LOD${detail}`,
          parts,
          tris:
            triangleCount(structure) + triangleCount(fittings) + triangleCount(concrete),
        });
      }
      const entry = ron(type, variant, height);
      files.push({ variant, levels, entry });
      rows.push({
        id: type.id,
        file: entry.file,
        tris: levels.map((l) => l.tris),
        height,
      });
    }

    if (!write) continue;
    const bin = `${stem(type.id)}.bin`;
    writeBuffer(assetDir, bin, buffer.toBuffer());
    for (const { variant, levels, entry } of files) {
      writeGltf({
        path: join(assetDir, `${entry.file}.gltf`),
        name: entry.file,
        buffer: bin,
        bufferLength: buffer.length,
        levels: levels.map((l) => ({ name: l.name, parts: l.parts })),
        materials: materialsOf(type, maps),
        images,
        copyright: COPYRIGHT,
      });
      writeFileSync(join(objectDir, `${entry.file}.ron`), entry.text, 'utf8');
      void variant;
    }
  }

  if (report || write) {
    let total = 0;
    for (const r of rows) {
      total += r.tris[0];
      console.log(
        `${r.file.padEnd(34)} ${r.height.toFixed(0).padStart(3)} m  ` +
          r.tris.map((t) => String(t).padStart(6)).join(' '),
      );
    }
    console.log(`${rows.length} variants, ${total} triangles at LOD0`);
  }
  return rows;
}

function manifest(count) {
  return `// Generated by tools/pylons/build_pylons.mjs — see tools/pylons/README.md.
(
    id: "pylons",
    name: "Freileitungsmasten",
    version: "1.0.0",
    author: "Connected Rails",
    description: "Die Masten der deutschen Freileitungen: Hoch- und Höchstspannung, Bahnstrom, Mittel- und Niederspannung sowie der Streckenfernmeldemast — ${count} Varianten, parametrisch aus dem Atlas erzeugt.",
    depends: [],
    enabled: true,
)
`;
}

function main() {
  const args = process.argv.slice(2);
  const only = args.find((a) => a.startsWith('--only='))?.slice(7)
    ?? (args.includes('--only') ? args[args.indexOf('--only') + 1] : null);
  const report = args.includes('--report');
  const preview = args.includes('--preview');
  const measureInk = args.includes('--ink');
  const check = args.includes('--check');

  const atlas = JSON.parse(readFileSync(join(here, 'pylons.json'), 'utf8'));
  let types = atlas.types;
  if (only) {
    const wanted = new Set(only.split(',').map((s) => s.trim()));
    types = types.filter((t) => wanted.has(t.id));
    const missing = [...wanted].filter((w) => !atlas.types.some((t) => t.id === w));
    if (missing.length) {
      console.error(`no such type: ${missing.join(', ')}`);
      process.exit(1);
    }
  }

  if (measureInk) {
    console.log('type                            level  at [m]   ink    vs finer');
    let worst = 0;
    for (const row of inkReport(types, (t) => lodDistances(t, (t.height_m[0] + t.height_m[1]) / 2))) {
      for (const level of row.line) {
        if (level.detail === 0) continue;
        if (level.unused) {
          console.log(
            `${row.type.id.padEnd(30)} LOD${level.detail}  ${String(Math.round(level.at)).padStart(5)}  ` +
              '   —      never drawn',
          );
          continue;
        }
        const off = Math.abs(level.ratio - 1);
        if (off > worst) worst = off;
        console.log(
          `${row.type.id.padEnd(30)} LOD${level.detail}  ${String(Math.round(level.at)).padStart(5)}  ` +
            `${level.coarse.toFixed(4)}  ${(level.ratio * 100).toFixed(0).padStart(4)} %`,
        );
      }
    }
    console.log(`worst hand-over is ${(worst * 100).toFixed(0)} % off`);
    return;
  }

  if (check) {
    // Every triangle of every level of every variant has to face outward. The
    // silhouette is the same either way, so nothing short of this catches a
    // primitive wound inside out — and `member` was, for the whole life of the
    // kit, which put four hundred bars per mast behind their own far faces.
    let bad = 0;
    for (const type of types) {
      for (const variant of variantsOf(type)) {
        for (let detail = 0; detail < 4; detail++) {
          const parts = buildMast(type, {
            role: variant.role,
            height: (type.height_m[0] + type.height_m[1]) / 2,
            detail,
          });
          for (const [what, geometry] of Object.entries(parts)) {
            const { inward } = facing(geometry);
            if (inward) {
              bad += inward;
              console.error(
                `${type.id}_${variant.suffix || 'x'} LOD${detail} ${what}: ` +
                  `${inward} triangles face inward`,
              );
            }
          }
        }
      }
    }
    if (bad) {
      console.error(`${bad} inward-facing triangles`);
      process.exit(1);
    }
    console.log(`all ${types.length} types face outward at every level`);
    return;
  }

  if (preview) {
    const out = renderSheet(types, '/tmp/pylon-preview');
    renderHandovers(types, '/tmp/pylon-preview', (t) =>
      lodDistances(t, (t.height_m[0] + t.height_m[1]) / 2),
    );
    console.log(`${out} sheets and ${types.length} hand-over sheets in /tmp/pylon-preview`);
    return;
  }

  if (report) {
    build(types, { write: false, report: true });
    return;
  }

  mkdirSync(assetDir, { recursive: true });
  mkdirSync(objectDir, { recursive: true });
  // A type dropped from the atlas has to lose its files too, or the mod keeps
  // serving a mast nobody can find in the catalogue any more.
  if (!only) {
    for (const dir of [assetDir, objectDir]) {
      for (const f of readdirSync(dir)) rmSync(join(dir, f));
    }
  }
  const rows = build(types, { write: true, report: false });
  if (!only) writeFileSync(join(modDir, 'mod.ron'), manifest(rows.length), 'utf8');
}

main();
