#!/usr/bin/env node
// Turns the atlas into the `pylons` mod: one glTF per mast variant, four levels
// of detail each, plus the `objects/*.ron` a route places and the manifest.
//
//   pylons.json ──build_pylons.mjs──▶ mods/pylons/assets/<type>_<role>.gltf
//               │      (lib/kit)                       + <type>.bin
//               └──────────────────▶ mods/pylons/objects/<type>_<role>.ron
//                                    mods/pylons/mod.ron
//
// Node 20 or newer and nothing else — no npm dependency, no image library, no
// modelling tool. Every triangle in `mods/pylons/` comes out of `lib/kit.mjs`
// and the numbers in `pylons.json`, which is the point: a mast whose crossarm
// is 40 cm too short is a one-line edit to the catalogue and a re-run, not an
// afternoon in Blender.
//
//   node tools/pylons/build_pylons.mjs
//   node tools/pylons/build_pylons.mjs --only donaumast-380,bahnstrommast-110
//   node tools/pylons/build_pylons.mjs --report     # triangle budget, writes nothing
//   node tools/pylons/build_pylons.mjs --preview    # a picture sheet into /tmp
//   node tools/pylons/build_pylons.mjs --ink        # what each level does to the mast's ink

import { mkdirSync, readFileSync, writeFileSync, readdirSync, rmSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { encodePng } from '../trees/lib/png.mjs';
import { MEMBER_SCALE, bodyMember, buildMast, finestMember } from './lib/kit.mjs';
import { paint } from './lib/texture.mjs';
import { facing, triangleCount } from './lib/geom.mjs';
import { BufferBuilder, writeGltf, writeBuffer } from './lib/gltf.mjs';
import { inkReport, renderHandovers, renderSheet } from './lib/preview.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const modDir = join(repo, 'mods', 'pylons');
const assetDir = join(modDir, 'assets');
const objectDir = join(modDir, 'objects');

const COPYRIGHT = 'Connected Rails, EUPL v. 1.2 — generated by tools/pylons/build_pylons.mjs';

/**
 * How big the painted maps are.
 *
 * 1024 px over a metre is **one millimetre a texel**, and it is the number the
 * painters' frequency budget is cut for: nothing they draw goes above a quarter
 * of it in cycles per metre (`lib/texture.mjs`). 512 px was mathematically
 * adequate, but the mip chain made its four-texel features visibly blocky in a
 * close camera. One millimetre leaves enough headroom for zinc orange-peel,
 * concrete pores and wood fibre without drawing sub-pixel noise.
 */
const TEXTURE_SIZE = 1024;
/** A LOD hand-over outside this band is visible as a mast changing weight. */
const MAX_INK_ERROR = 0.20;

/**
 * What the steel, the concrete and the wood look like.
 *
 * The base colour, the roughness and the metallic all come out of the painted
 * maps (`lib/texture.mjs`), so the factors here are **one**: in glTF a factor
 * multiplies its texture, and anything but one would be a second opinion about
 * a number the map already has. What is left for the material to say is that
 * this is metal and that is not.
 */
const MATERIALS = {
  'steel-lattice': { name: 'verzinkt', structure: 'steel-lattice', normalScale: 0.36 },
  // A tube's UV tangent changes at every mesh segment even though its vertex
  // normal is smooth. A tangent-space map therefore draws a vertical seam at
  // every segment; zinc relief is too shallow to justify that artefact.
  'steel-tube': { name: 'stahlrohr', structure: 'steel-tube', normalScale: null },
  'spun-concrete': { name: 'schleuderbeton', structure: 'spun-concrete', normalScale: 0.58 },
  wood: { name: 'holz', structure: 'wood', normalScale: 0.72 },
};

/**
 * The fittings, which stay constants.
 *
 * An insulator is glazed porcelain or moulded silicone: smooth, so there is no
 * microstructure worth a roughness map, and small, so there is no room for one
 * to show. A cap-and-pin string is the brown of a fired glaze; the double-bell
 * porcelain of a telegraph pole is white, which is how you can pick a telegraph
 * pole out of a hedge at two hundred metres. Modern composite long rods are the
 * neutral grey of weathered silicone.
 *
 * **`baseColorFactor` is linear, and that is what went wrong here.** The brown
 * was written as if it were sRGB — 0.40, 0.30, 0.24 is linear 0.40, which is
 * sRGB 168, a milky cream — and under the sky's image-based light at a
 * roughness of 0.24 the strings came out pale pink. Fired brown glaze is
 * sRGB 94, 58, 44, which is the linear triple below; the gloss is down as well,
 * because a string that has hung in the weather for thirty years is glazed, not
 * polished.
 */
const FITTING_MATERIAL = {
  suspension: { name: 'isolator', color: [0.111, 0.043, 0.026, 1], metallic: 0, roughness: 0.32 },
  // Weathered HTV silicone is a light, neutral grey and appreciably duller
  // than glazed porcelain. Values are linear, as glTF requires.
  composite: { name: 'silikonisolator', color: [0.263, 0.278, 0.292, 1], metallic: 0, roughness: 0.58 },
  pin: { name: 'isolator', color: [0.120, 0.048, 0.029, 1], metallic: 0, roughness: 0.30 },
  spool: { name: 'niederspannungs_porzellan', color: [0.55, 0.53, 0.48, 1], metallic: 0, roughness: 0.30 },
  bell: { name: 'porzellan', color: [0.72, 0.70, 0.65, 1], metallic: 0, roughness: 0.22 },
};

// The whole printed face is one 1024 px PBR texture. Building letters and the
// lightning flash from hundreds of millimetre-wide coplanar triangles made the
// depth buffer shimmer in a close moving camera; a mipmapped decal is both the
// physically correct construction and the stable one.
const SIGN_MATERIAL = {
  name: 'warnschild_bedruckt',
  color: [1, 1, 1, 1],
  metallic: 1,
  roughness: 1,
  normalScale: 0.12,
};
const MARKING_MATERIAL = {
  name: 'warnschild_schwarz',
  color: [0.006, 0.006, 0.006, 1],
  metallic: 0,
  roughness: 0.58,
};

/**
 * The variants of one type: which roles the atlas says it is built in.
 *
 * Height is *not* a variant. The atlas gives a band, the placement gives a
 * scale, and a mast scaled by a tenth either way is the same drawing built
 * taller — which is what a manufacturer does too. Two files per type instead of
 * eight, and a line of Donaumasten still varies along its length.
 */
function variantsOf(type) {
  const roles = type.roles ?? [];
  const out = [];
  if (roles.includes('suspension')) out.push({ role: 'suspension', suffix: 'trag', label: 'Tragmast' });
  if (roles.includes('tension')) out.push({ role: 'tension', suffix: 'abspann', label: 'Abspannmast' });
  if (out.length === 0) out.push({ role: 'suspension', suffix: '', label: '' });
  return out;
}

/** Fails catalogue typos before a missing fitting silently becomes geometry. */
function validateTypes(types) {
  for (const type of types) {
    const b = type.build;
    if (!FITTING_MATERIAL[b.fitting]) {
      throw new Error(`${type.id}: unknown fitting '${b.fitting}'`);
    }
    if (!(b.insulator_m > 0)) {
      throw new Error(`${type.id}: insulator_m must be positive`);
    }
    const field = b.fitting === 'composite' ? 'insulator_sheds' : 'insulator_discs';
    if (!Number.isInteger(b[field]) || b[field] < 1) {
      throw new Error(`${type.id}: ${field} must be a positive integer`);
    }
    // On a trussed or tubular support, an arm is joined to the body by both
    // chords. Letting the upper root joint rise above the body makes a floating
    // triangle which can look plausible from one side but cannot carry load.
    // Flat pole brackets are different: their depth describes the brace below
    // the conductor level and is therefore deliberately excluded here.
    if (b.kind !== 'pole') {
      const height = (type.height_m[0] + type.height_m[1]) / 2;
      const bodyTop = height - (b.peaks > 0 ? b.peak_m : 0);
      for (const arm of type.crossarms) {
        const rootTop = arm.at_frac * height + arm.depth_m;
        if (rootTop > bodyTop + 0.05) {
          throw new Error(
            `${type.id}: crossarm root at ${rootTop.toFixed(2)} m exceeds ` +
            `the ${bodyTop.toFixed(2)} m body top`,
          );
        }
      }
    }
  }
}

/** Refuse to export a visually flat or accidentally incomplete material. */
function validatePbrMaterials(type, materials) {
  for (const material of materials) {
    if (!Array.isArray(material.color) || material.color.length !== 4 ||
        !material.color.every(Number.isFinite)) {
      throw new Error(`${type.id}/${material.name}: invalid PBR base colour`);
    }
    for (const field of ['metallic', 'roughness']) {
      if (!Number.isFinite(material[field]) || material[field] < 0 || material[field] > 1) {
        throw new Error(`${type.id}/${material.name}: invalid PBR ${field}`);
      }
    }
    if (material.maps) {
      for (const map of ['colour', 'orm']) {
        if (!Number.isInteger(material.maps[map])) {
          throw new Error(`${type.id}/${material.name}: missing PBR ${map} map`);
        }
      }
    }
  }
}

/** Audit the actual shipped glTF and PNG files, not only their JS inputs. */
function validateGeneratedPbr(types) {
  let bad = 0;
  const seenImages = new Set();
  for (const type of types) {
    for (const variant of variantsOf(type)) {
      const file = variant.suffix ? `${stem(type.id)}_${variant.suffix}` : stem(type.id);
      const path = join(assetDir, `${file}.gltf`);
      if (!existsSync(path)) {
        console.error(`${file}: generated glTF is missing`);
        bad++;
        continue;
      }
      const gltf = JSON.parse(readFileSync(path, 'utf8'));
      for (const material of gltf.materials ?? []) {
        const pbr = material.pbrMetallicRoughness;
        const color = pbr?.baseColorFactor;
        if (!pbr || !Array.isArray(color) || color.length !== 4 ||
            !color.every(Number.isFinite) || !Number.isFinite(pbr.metallicFactor) ||
            !Number.isFinite(pbr.roughnessFactor) || material.doubleSided !== false) {
          console.error(`${file}/${material.name}: incomplete glTF PBR material`);
          bad++;
        }
      }
      for (const image of gltf.images ?? []) {
        if (seenImages.has(image.uri)) continue;
        seenImages.add(image.uri);
        const imagePath = join(assetDir, image.uri);
        if (!existsSync(imagePath)) {
          console.error(`${file}: missing PBR image ${image.uri}`);
          bad++;
          continue;
        }
        const png = readFileSync(imagePath);
        const isPng = png.length >= 24 && png.subarray(1, 4).toString('ascii') === 'PNG';
        const width = isPng ? png.readUInt32BE(16) : 0;
        const height = isPng ? png.readUInt32BE(20) : 0;
        if (width !== TEXTURE_SIZE || height !== TEXTURE_SIZE) {
          console.error(
            `${image.uri}: ${width}x${height}, expected ${TEXTURE_SIZE}x${TEXTURE_SIZE}`,
          );
          bad++;
        }
      }
    }
  }
  if (bad) throw new Error(`${bad} generated PBR asset errors`);
  return seenImages.size;
}

const stem = (id) => id.replaceAll('-', '_');

/**
 * One pixel, in metres, per metre of distance.
 *
 * The reference the bands are cut for is **1440 lines at the simulator's 45°
 * vertical field of view** — `2 * tan(fov / 2) / lines`. A finer screen resolves
 * a member further out and gets a slightly conservative hand-over; a coarser one
 * a slightly late. That is the same assumption `tools/trees` makes, and it is
 * worth stating rather than hiding: judge a level at the resolution it will be
 * played at, or it will be judged wrong.
 */
const METRES_PER_PIXEL_PER_METRE = (2 * Math.tan(Math.PI / 8)) / 1440;

/**
 * Where the levels hand over [m], for one type.
 *
 * **The mast's height is the wrong thing to scale by**, which is what the first
 * cut of this did. What decides whether a level is still worth its triangles is
 * not how tall the mast is but how thin its *members* are: a 12 m concrete pole
 * with a 9 cm crossarm and a 60 m Donaumast with a 16 cm brace resolve at almost
 * the same distance, and a rule in units of the height puts them a factor of
 * five apart. So the bands come off the geometry:
 *
 * - **LOD0 → LOD1** where the thinnest member drops below a pixel. Past that it
 *   is not drawn, it is *sampled* — some pixel centres hit, others missed, and
 *   the pattern crawls as the camera moves. That is the same failure the
 *   conductors have, and the mast cannot be fixed the same way: a lattice is
 *   three hundred members going in every direction, not one line.
 * - **LOD1 → LOD2** where half the panels, drawn a fifth thicker, have gone the
 *   same way — about two and a half times further out.
 * - **LOD2 → LOD3** where the mast's **body** is under two pixels wide. That is
 *   the honest end of the lattice: below two pixels there is no room for two
 *   legs and a gap between them, so there is nothing inside the outline left to
 *   draw and the bracing finally goes. A pole has nothing inside it to begin
 *   with, so it hands over where its own shaft stops resolving instead.
 * - **Culled** where the whole mast is ten pixels tall. On a 380 kV Donaumast
 *   that is ten kilometres, so the cap decides instead: four kilometres, which
 *   is past where the terrain under it is still built. A 7.5 m telegraph pole
 *   goes at 1.3 km, where it is a tenth of a pixel wide.
 */
function lodDistances(type, height) {
  const perPixel = (metres, pixels) => metres / (pixels * METRES_PER_PIXEL_PER_METRE);
  const finest = finestMember(type);
  const cull = Math.min(4000, Math.max(700, perPixel(height, 10)));
  const lattice = type.build.kind === 'lattice' || type.build.kind === 'portal';
  const bands = [
    perPixel(finest, 1.0),
    perPixel(finest * MEMBER_SCALE[1], 0.55),
    lattice
      ? perPixel(type.build.shaft_m, 2.0)
      : perPixel(bodyMember(type) * MEMBER_SCALE[2], 0.6),
    cull,
  ];
  // Monotone and inside the cull, whatever the proportions of an odd type do.
  let previous = 0;
  return bands.map((d) => {
    const clamped = Math.min(Math.max(d, previous + 1), cull);
    previous = clamped;
    return Math.round(clamped);
  });
}

function ron(type, variant, height) {
  const name = variant.label ? `${type.name_de} (${variant.label})` : type.name_de;
  const file = variant.suffix ? `${stem(type.id)}_${variant.suffix}` : stem(type.id);
  const tags = [...type.tags];
  if (variant.suffix) tags.push(variant.suffix);
  const lod = lodDistances(type, height);
  return {
    file,
    text: `// ${name}, ${height.toFixed(0)} m — generated by tools/pylons/build_pylons.mjs;
// edit pylons.json, not this file.
(
    name: "${name}",
    model: "pylons/assets/${file}.gltf",
    lateral_offset: 0.0,
    yaw_deg: 0.0,
    height: 0.0,
    lod_distances: [${lod.join(', ')}],
    tags: [${tags.map((t) => `"${t}"`).join(', ')}],
)
`,
  };
}

/**
 * Paints the three tiling maps of every construction material and writes them
 * beside the models, once. The printed warning face adds one non-tiling PBR
 * triplet, so the whole catalogue shares twelve PNGs.
 *
 * Returns the image list and, per material, where its maps sit in it.
 */
function paintTextures(types, write) {
  const kinds = [...new Set(types.map((t) => t.structure))];
  // Every support can carry galvanised fittings (climbing irons, brackets,
  // transformer steel), including an `--only` build of a wooden pole.
  if (!kinds.includes('steel-lattice')) kinds.push('steel-lattice');
  // The foundations are concrete whatever the mast is made of.
  if (types.some((t) => t.build.kind === 'lattice' || t.build.kind === 'portal')) {
    if (!kinds.includes('spun-concrete')) kinds.push('spun-concrete');
  }
  // Concrete poles still have galvanised crossarms and brackets. This matters
  // for `--only betonmast-…`, where no lattice type would otherwise request
  // the shared zinc maps that their hardware uses.
  if (types.some((t) => t.structure === 'spun-concrete')) {
    if (!kinds.includes('steel-lattice')) kinds.push('steel-lattice');
  }
  const images = [];
  const maps = {};
  // Keyed on the painter's own id, not on the structure: a steel tube and a
  // steel lattice are the same zinc, and painting it twice would ship the same
  // three files under two names.
  const byId = new Map();
  for (const kind of kinds) {
    const painted = paint(kind, TEXTURE_SIZE);
    if (!byId.has(painted.id)) {
      const slots = {};
      for (const map of ['colour', 'orm', 'normal']) {
        const file = `${painted.id}_${map}.png`;
        slots[map] = images.length;
        images.push(file);
        if (write) {
          writeFileSync(join(assetDir, file), encodePng(painted[map], TEXTURE_SIZE, TEXTURE_SIZE));
        }
      }
      byId.set(painted.id, slots);
    }
    maps[kind] = byId.get(painted.id);
  }

  // A sign is not a tiling construction material. Its source is a deliberately
  // flat, orthographic 1024 px plate face under `tools/pylons/assets`; copy the
  // albedo and generate neutral physical maps beside the shared structure maps.
  // Keeping the source outside `mods/pylons/assets` matters because a full build
  // clears that generated directory before recreating it.
  const sign = {};
  const signColour = 'warnschild_colour.png';
  sign.colour = images.length;
  images.push(signColour);
  const solidMap = (rgba) => {
    const data = new Uint8Array(TEXTURE_SIZE * TEXTURE_SIZE * 4);
    for (let i = 0; i < data.length; i += 4) {
      data[i] = rgba[0];
      data[i + 1] = rgba[1];
      data[i + 2] = rgba[2];
      data[i + 3] = rgba[3];
    }
    return data;
  };
  for (const [slot, file, rgba] of [
    ['orm', 'warnschild_orm.png', [255, 142, 0, 255]],
    ['normal', 'warnschild_normal.png', [128, 128, 255, 255]],
  ]) {
    sign[slot] = images.length;
    images.push(file);
    if (write) {
      writeFileSync(join(assetDir, file), encodePng(solidMap(rgba), TEXTURE_SIZE, TEXTURE_SIZE));
    }
  }
  if (write) {
    const source = readFileSync(join(here, 'assets', signColour));
    const width = source.length >= 24 ? source.readUInt32BE(16) : 0;
    const height = source.length >= 24 ? source.readUInt32BE(20) : 0;
    if (width !== TEXTURE_SIZE || height !== TEXTURE_SIZE) {
      throw new Error(`${signColour}: ${width}x${height}, expected ${TEXTURE_SIZE}x${TEXTURE_SIZE}`);
    }
    writeFileSync(join(assetDir, signColour), source);
  }
  maps['warning-sign'] = sign;
  return { images, maps };
}

/** The structure, fitting, foundation and optional hardware materials. */
function materialsOf(type, maps) {
  const structure = MATERIALS[type.structure];
  const fitting = FITTING_MATERIAL[type.build.fitting];
  if (!fitting) throw new Error(`${type.id}: unknown fitting '${type.build.fitting}'`);
  const white = [1, 1, 1, 1];
  const materials = [
    {
      name: structure.name,
      color: white,
      // One, because the map has the number. A factor here would be a second
      // opinion about it.
      metallic: 1,
      roughness: 1,
      normalScale: structure.normalScale,
      maps: maps[type.structure],
    },
    fitting,
    {
      name: 'fundament',
      color: white,
      metallic: 1,
      roughness: 1,
      normalScale: 1.0,
      maps: maps['spun-concrete'],
    },
  ];
  if (maps['steel-lattice']) {
    const steel = MATERIALS['steel-lattice'];
    materials.push({
      name: 'beschlaege_verzinkt',
      color: white,
      metallic: 1,
      roughness: 1,
      normalScale: steel.normalScale,
      maps: maps['steel-lattice'],
    });
  }
  materials.push({ ...SIGN_MATERIAL, maps: maps['warning-sign'] }, MARKING_MATERIAL);
  return materials;
}

function build(types, { write, report }) {
  const { images, maps } = paintTextures(types, write);
  const rows = [];
  for (const type of types) {
    const height = (type.height_m[0] + type.height_m[1]) / 2;
    const buffer = new BufferBuilder();
    const files = [];

    for (const variant of variantsOf(type)) {
      const levels = [];
      for (let detail = 0; detail < 4; detail++) {
        const { structure, fittings, concrete, hardware, signage, markings } = buildMast(type, {
          role: variant.role,
          height,
          detail,
        });
        const parts = [{ packed: buffer.add(structure), material: 0 }];
        if (fittings.positions.length) parts.push({ packed: buffer.add(fittings), material: 1 });
        if (concrete.positions.length) parts.push({ packed: buffer.add(concrete), material: 2 });
        if (hardware.positions.length) parts.push({ packed: buffer.add(hardware), material: 3 });
        if (signage.positions.length) parts.push({ packed: buffer.add(signage), material: 4 });
        if (markings.positions.length) parts.push({ packed: buffer.add(markings), material: 5 });
        levels.push({
          name: `mast_LOD${detail}`,
          parts,
          tris:
            triangleCount(structure) + triangleCount(fittings) +
            triangleCount(concrete) + triangleCount(hardware) +
            triangleCount(signage) + triangleCount(markings),
        });
      }
      const entry = ron(type, variant, height);
      files.push({ variant, levels, entry });
      rows.push({
        id: type.id,
        file: entry.file,
        tris: levels.map((l) => l.tris),
        height,
      });
    }

    if (!write) continue;
    const bin = `${stem(type.id)}.bin`;
    writeBuffer(assetDir, bin, buffer.toBuffer());
    for (const { variant, levels, entry } of files) {
      const materials = materialsOf(type, maps);
      validatePbrMaterials(type, materials);
      writeGltf({
        path: join(assetDir, `${entry.file}.gltf`),
        name: entry.file,
        buffer: bin,
        bufferLength: buffer.length,
        levels: levels.map((l) => ({ name: l.name, parts: l.parts })),
        materials,
        images,
        copyright: COPYRIGHT,
      });
      writeFileSync(join(objectDir, `${entry.file}.ron`), entry.text, 'utf8');
      void variant;
    }
  }

  if (report || write) {
    let total = 0;
    for (const r of rows) {
      total += r.tris[0];
      console.log(
        `${r.file.padEnd(34)} ${r.height.toFixed(0).padStart(3)} m  ` +
          r.tris.map((t) => String(t).padStart(6)).join(' '),
      );
    }
    console.log(`${rows.length} variants, ${total} triangles at LOD0`);
  }
  return rows;
}

function manifest(count) {
  return `// Generated by tools/pylons/build_pylons.mjs — see tools/pylons/README.md.
(
    id: "pylons",
    name: "Freileitungsmasten",
    version: "1.0.0",
    author: "Connected Rails",
    description: "Die Masten der deutschen Freileitungen: Hoch- und Höchstspannung, Bahnstrom, Mittel- und Niederspannung sowie der Streckenfernmeldemast — ${count} Varianten, parametrisch aus dem Atlas erzeugt.",
    depends: [],
    enabled: true,
)
`;
}

function main() {
  const args = process.argv.slice(2);
  const only = args.find((a) => a.startsWith('--only='))?.slice(7)
    ?? (args.includes('--only') ? args[args.indexOf('--only') + 1] : null);
  const report = args.includes('--report');
  const preview = args.includes('--preview');
  const measureInk = args.includes('--ink');
  const check = args.includes('--check');

  const atlas = JSON.parse(readFileSync(join(here, 'pylons.json'), 'utf8'));
  let types = atlas.types;
  if (only) {
    const wanted = new Set(only.split(',').map((s) => s.trim()));
    types = types.filter((t) => wanted.has(t.id));
    const missing = [...wanted].filter((w) => !atlas.types.some((t) => t.id === w));
    if (missing.length) {
      console.error(`no such type: ${missing.join(', ')}`);
      process.exit(1);
    }
  }
  validateTypes(types);

  if (measureInk) {
    console.log('type                            level  at [m]   ink    vs finer');
    let worst = 0;
    for (const row of inkReport(types, (t) => lodDistances(t, (t.height_m[0] + t.height_m[1]) / 2))) {
      for (const level of row.line) {
        if (level.detail === 0) continue;
        if (level.unused) {
          console.log(
            `${row.type.id.padEnd(30)} LOD${level.detail}  ${String(Math.round(level.at)).padStart(5)}  ` +
              '   —      never drawn',
          );
          continue;
        }
        const off = Math.abs(level.ratio - 1);
        if (off > worst) worst = off;
        console.log(
          `${row.type.id.padEnd(30)} LOD${level.detail}  ${String(Math.round(level.at)).padStart(5)}  ` +
            `${level.coarse.toFixed(4)}  ${(level.ratio * 100).toFixed(0).padStart(4)} %`,
        );
      }
    }
    console.log(`worst hand-over is ${(worst * 100).toFixed(0)} % off`);
    if (worst > MAX_INK_ERROR) {
      console.error(`LOD ink exceeds the ${(MAX_INK_ERROR * 100).toFixed(0)} % limit`);
      process.exitCode = 1;
    }
    return;
  }

  if (check) {
    // Every triangle of every level of every variant has to face outward. The
    // silhouette is the same either way, so nothing short of this catches a
    // primitive wound inside out — and `member` was, for the whole life of the
    // kit, which put four hundred bars per mast behind their own far faces.
    let bad = 0;
    for (const type of types) {
      for (const variant of variantsOf(type)) {
        for (let detail = 0; detail < 4; detail++) {
          const parts = buildMast(type, {
            role: variant.role,
            height: (type.height_m[0] + type.height_m[1]) / 2,
            detail,
          });
          // Terrain is a surface rather than a closed volume. A pole that runs
          // below its placement origin shows its buried side triangles through
          // that surface as a pair of points around a semicircular cut-out.
          if (type.build.kind === 'pole') {
            let bottom = Infinity;
            for (let i = 1; i < parts.structure.positions.length; i += 3) {
              bottom = Math.min(bottom, parts.structure.positions[i]);
            }
            if (Math.abs(bottom) > 1e-6) {
              bad++;
              console.error(
                `${type.id}_${variant.suffix || 'x'} LOD${detail}: ` +
                  `pole bottom ${bottom.toFixed(2)} m is not on its placement plane`,
              );
            }
          }
          for (const [what, geometry] of Object.entries(parts)) {
            const { inward } = facing(geometry);
            if (inward) {
              bad += inward;
              console.error(
                `${type.id}_${variant.suffix || 'x'} LOD${detail} ${what}: ` +
                  `${inward} triangles face inward`,
              );
            }
          }
        }
      }
    }
    if (bad) {
      console.error(`${bad} inward-facing triangles`);
      process.exit(1);
    }
    const images = validateGeneratedPbr(types);
    console.log(
      `all ${types.length} types face outward at every level; ` +
      `every glTF material is PBR and ${images} referenced maps are ${TEXTURE_SIZE}px`,
    );
    return;
  }

  if (preview) {
    const out = renderSheet(types, '/tmp/pylon-preview');
    renderHandovers(types, '/tmp/pylon-preview', (t) =>
      lodDistances(t, (t.height_m[0] + t.height_m[1]) / 2),
    );
    console.log(`${out} sheets and ${types.length} hand-over sheets in /tmp/pylon-preview`);
    return;
  }

  if (report) {
    build(types, { write: false, report: true });
    return;
  }

  mkdirSync(assetDir, { recursive: true });
  mkdirSync(objectDir, { recursive: true });
  // A type dropped from the atlas has to lose its files too, or the mod keeps
  // serving a mast nobody can find in the catalogue any more.
  if (!only) {
    for (const dir of [assetDir, objectDir]) {
      for (const f of readdirSync(dir)) rmSync(join(dir, f));
    }
  }
  const rows = build(types, { write: true, report: false });
  if (!only) writeFileSync(join(modDir, 'mod.ron'), manifest(rows.length), 'utf8');
}

main();
