"""Procedural signal part models for the example mod.

Writes three glTF files below mods/example/assets/ — created entirely from
scratch in this script, no third-party assets, so the files carry the
project's licence:

  sig_mast.gltf        mast with base plate; mount point ``mp_schirm``.
                       Two levels of detail (mast_LOD0/mast_LOD1)
  sig_schirm_ks.gltf   Ks screen with lamp nodes lamp_red/green/yellow/zs1
                       and the mount point ``mp_top`` for a Zs3
  sig_zs3.gltf         Zs3 speed indicator board with the digit node ``zs3_4``

The full-size semaphore family, including the backwards-compatible
``sig_form_hp.gltf`` alias, is generated by ``gen_form_signals.py``.

Conventions per MODS.md: origin at the part's attachment (the mast at its foot
on rail-top height), +Y up, the face towards the approaching driver looks
along +Z. Mount points are empty nodes named ``mp_*``; lamps are meshes the
app switches by visibility, so a lit lens sits proud of a dark housing that
stays visible.

Run: python tools/gen_signal_parts.py
"""

import base64
import functools
import json
import math
import random
import struct
import zlib
from pathlib import Path

ASSETS = Path(__file__).resolve().parents[1] / "mods" / "example" / "assets"
SIGNAL_TEXTURES = ASSETS / "textures" / "signals"

COPYRIGHT = (
    "Connected Rails project. Procedural model built from scratch in "
    "tools/gen_signal_parts.py, no third-party assets; licensed like the project."
)


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def normalize(v):
    l = math.sqrt(dot(v, v))
    return (v[0] / l, v[1] / l, v[2] / l)


class Prim:
    """One glTF primitive: flat-shaded triangles with per-face normals and UVs."""

    def __init__(self):
        self.pos, self.nrm, self.uv, self.idx = [], [], [], []

    def tri(self, a, b, c, uvs=None):
        n = normalize(cross(sub(b, a), sub(c, a)))
        base = len(self.pos)
        self.pos += [a, b, c]
        self.nrm += [n, n, n]
        # A deterministic fallback projection keeps older generators compatible.
        # New geometry can provide face-local UVs for clean, repeatable weathering.
        self.uv += list(uvs or ((a[0] + a[2], a[1]),
                                (b[0] + b[2], b[1]),
                                (c[0] + c[2], c[1])))
        self.idx += [base, base + 1, base + 2]

    def quad(self, a, b, c, d):  # corners CCW seen from outside
        # World-scale face-local UVs keep a 128 px material tile sharp on an
        # eight-metre mast instead of stretching 64 pixels over its full height.
        # Four repeats per metre give paint/oxide detail at roughly 2.5 cm scale.
        repeat = 4.0
        u = max(0.35, math.dist(a, b) * repeat)
        v = max(0.35, math.dist(b, c) * repeat)
        self.tri(a, b, c, ((0.0, 0.0), (u, 0.0), (u, v)))
        self.tri(a, c, d, ((0.0, 0.0), (u, v), (0.0, v)))

    def box(self, mn, mx):
        x0, y0, z0 = mn
        x1, y1, z1 = mx
        self.quad((x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1))  # +X
        self.quad((x0, y0, z1), (x0, y1, z1), (x0, y1, z0), (x0, y0, z0))  # -X
        self.quad((x0, y1, z0), (x0, y1, z1), (x1, y1, z1), (x1, y1, z0))  # +Y
        self.quad((x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1))  # -Y
        self.quad((x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1))  # +Z
        self.quad((x1, y0, z0), (x0, y0, z0), (x0, y1, z0), (x1, y1, z0))  # -Z


def _png_rgba(width, height, pixels):
    """Tiny dependency-free PNG writer used for embedded procedural PBR maps."""
    stride = width * 4
    raw = b"".join(b"\0" + bytes(pixels[y * stride:(y + 1) * stride])
                   for y in range(height))

    def chunk(kind, data):
        return (struct.pack(">I", len(data)) + kind + data
                + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF))

    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


@functools.lru_cache(maxsize=None)
def _texture_maps(profile, size=128):
    """Sharp repeatable PBR micro-detail: colour wear, ORM and normal map."""
    if profile in ("optical-glass", "led-optical-glass"):
        # Signal lenses are polished optical glass, not paint. Their visible
        # Fresnel structure comes from the curved mesh; this map stays almost
        # perfectly smooth and only breaks up an unrealistically ideal highlight.
        colour, orm, normal = [], [], []
        for y in range(size):
            for x in range(size):
                amplitude = 0.0012 if profile == "led-optical-glass" else 0.003
                wave = math.sin(x * 0.19 + y * 0.11) * amplitude
                value = int(255 * (0.994 + wave))
                colour.extend((value, value, value, 255))
                orm.extend((255, 72 + int(500 * abs(wave)), 0, 255))
                normal.extend((128, 128, 255, 255))
        return (_png_rgba(size, size, colour), _png_rgba(size, size, orm),
                _png_rgba(size, size, normal))

    if profile == "ne2-face":
        # DB S 525.1: one texture replaces the former stack of black/white
        # geometry.  A shallow height transition gives the black print/film a
        # restrained raised edge in the normal map without changing silhouette.
        def segment_distance(px, py, ax, ay, bx, by):
            dx, dy = bx - ax, by - ay
            t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy)
                                   / (dx * dx + dy * dy)))
            return math.hypot(px - (ax + t * dx), py - (ay + t * dy))

        coverage = []
        # The four diagonal bars meet the inner edge of the border at its
        # corners. This yields the four white triangular fields of S 525.1,
        # instead of the earlier detached, thin V marks.
        strokes = [((0.055, 0.945), (0.50, 0.50)),
                   ((0.50, 0.50), (0.945, 0.945)),
                   ((0.055, 0.055), (0.50, 0.50)),
                   ((0.50, 0.50), (0.945, 0.055))]
        for y in range(size):
            v = (y + 0.5) / size
            for x in range(size):
                u = (x + 0.5) / size
                edge_distance = min(u, 1.0 - u, v, 1.0 - v)
                line_distance = min(segment_distance(u, v, *a, *b)
                                    for a, b in strokes)
                signed = min(edge_distance - 0.050, line_distance - 0.060)
                # One-pixel antialias band at the black/white boundary.
                ink = max(0.0, min(1.0, 0.5 - signed * size))
                coverage.append(ink)
        colour, orm, normal = [], [], []
        heights = [0.50 + 0.055 * ink for ink in coverage]
        for y in range(size):
            for x in range(size):
                i = y * size + x
                ink = coverage[i]
                white, black = (0.90, 0.90, 0.86), (0.018, 0.018, 0.021)
                colour.extend(tuple(int(255 * (white[c] * (1.0 - ink)
                                                + black[c] * ink))
                                    for c in range(3)) + (255,))
                orm.extend((255, int(255 * (0.78 + 0.08 * ink)), 0, 255))
                dx = (heights[y * size + min(size - 1, x + 1)]
                      - heights[y * size + max(0, x - 1)])
                dy = (heights[min(size - 1, y + 1) * size + x]
                      - heights[max(0, y - 1) * size + x])
                nx, ny, nz = -dx * 3.0, -dy * 3.0, 1.0
                n = math.sqrt(nx * nx + ny * ny + nz * nz)
                normal.extend((int(127.5 * (nx / n + 1.0)),
                               int(127.5 * (ny / n + 1.0)),
                               int(127.5 * (nz / n + 1.0)), 255))
        return (_png_rgba(size, size, colour), _png_rgba(size, size, orm),
                _png_rgba(size, size, normal))

    seed = sum((i + 1) * ord(c) for i, c in enumerate(profile))
    rng = random.Random(seed)
    coarse = [rng.random() for _ in range(size * size)]
    fine = [rng.random() for _ in range(size * size)]
    # Broad substrate undulation plus preserved high-frequency paint grain.
    for _ in range(4):
        coarse = [
            sum(coarse[((y + dy) % size) * size + ((x + dx) % size)]
                for dy in (-1, 0, 1) for dx in (-1, 0, 1)) / 9.0
            for y in range(size) for x in range(size)
        ]
    height = []
    for y in range(size):
        for x in range(size):
            i = y * size + x
            grain = fine[i] - 0.5
            # Fine vertical run-off traces remain crisp after mipmapping.
            streak = 0.5 + 0.5 * math.sin((x * 0.47 + seed * 0.013))
            streak *= max(0.0, math.sin((y + seed % 31) * 0.105))
            mix = 0.78 * coarse[i] + 0.22 * (grain + 0.5)
            if profile == "enamel":
                # Vitreous enamel is a glass-smooth fired skin.  Its visible
                # age belongs at chips and damaged edges, not as coarse noise
                # across every intact colour field.  Retain only sub-millimetre
                # orange-peel so highlights are not mathematically perfect.
                # Encoding a clear but shallow height signal is intentional:
                # the material's small normal scale attenuates it after the
                # PNG's 8-bit quantisation instead of losing it altogether.
                mix = 0.50 + 0.035 * (coarse[i] - 0.5) + 0.014 * grain
                mix -= 0.003 * streak
            elif profile in {"painted", "black-paint"}:
                # Maintained signal paint is a continuous rolled/brushed film,
                # not the broad cloudy noise of the old 256-px map.  Low spots
                # and very restrained vertical run-off survive at close range;
                # chips, rust and water traps remain explicit geometry.
                mix = 0.50 + 0.11 * (coarse[i] - 0.5) + 0.035 * grain
                mix -= 0.012 * streak
            elif profile == "galvanised":
                mix = 0.50 + 0.18 * (coarse[i] - 0.5) + 0.055 * grain
                mix -= 0.014 * streak
            height.append(max(0.0, min(1.0, mix)))

    colour, orm, normal = [], [], []
    # Values are texture multipliers; the material factors retain control of
    # the physical base roughness/metalness instead of being multiplied twice.
    profile_response = {
        "galvanised": (0.92, 1.00, 0.85), "painted": (0.91, 1.00, 0.90),
        "enamel": (0.82, 1.00, 1.60), "black-paint": (0.94, 1.00, 0.95),
        "rust": (0.98, 1.00, 0.72), "concrete": (0.97, 1.00, 0.60),
        "glass": (0.82, 1.00, 0.08), "rubber": (0.98, 1.00, 0.38),
    }
    rough, metal, normal_strength = profile_response.get(profile, (0.92, 1.0, 0.30))
    for y in range(size):
        for x in range(size):
            i = y * size + x
            h = height[i]
            # Oxide/dust collects in low spots. Kept subtle because this tiles over
            # full-size geometry and dedicated rust/chip meshes add the macro wear.
            grime = max(0.0, 0.47 - h) * (0.55 if profile != "glass" else 0.08)
            warm = profile in {"galvanised", "painted", "enamel", "rust"}
            micro = fine[i] - 0.5
            if profile == "enamel":
                # Colour stays almost uniform on intact enamel; the geometry
                # generator adds the sparse chips/rust that should actually be
                # readable.  This prevents the old paper/felt appearance.
                grime *= 0.08
                shade = 0.992 + 0.018 * (h - 0.5) + 0.003 * micro
            elif profile in {"painted", "black-paint"}:
                # Keep the base-colour response much calmer than concrete or
                # oxide. Surface character comes primarily from roughness and
                # normals, so the paint stays crisp rather than fuzzy.
                grime *= 0.22
                shade = 0.985 + 0.030 * (h - 0.5) + 0.005 * micro
            else:
                shade = 0.935 + 0.105 * h + 0.030 * micro
            colour.extend((
                int(255 * min(1.0, max(0.0, shade - grime * (0.30 if warm else 0.18)))),
                int(255 * min(1.0, max(0.0, shade - grime * (0.55 if warm else 0.20)))),
                int(255 * min(1.0, max(0.0, shade - grime * (0.72 if warm else 0.22)))),
                255,
            ))
            if profile == "enamel":
                local_rough = min(0.90, max(0.72,
                    rough + grime * 0.06 + micro * 0.015))
                ao = int(255 * (0.992 + 0.008 * h))
            else:
                local_rough = min(1.0, max(0.55,
                    rough + grime * 0.22 + micro * 0.06))
                ao = int(255 * (0.94 + 0.06 * h))
            orm.extend((ao, int(255 * local_rough), int(255 * metal), 255))
            dx = height[y * size + ((x + 1) % size)] - height[y * size + ((x - 1) % size)]
            dy = height[((y + 1) % size) * size + x] - height[((y - 1) % size) * size + x]
            nx, ny, nz = -dx * normal_strength, -dy * normal_strength, 1.0
            length = math.sqrt(nx * nx + ny * ny + nz * nz)
            normal.extend((int(127.5 * (nx / length + 1.0)),
                           int(127.5 * (ny / length + 1.0)),
                           int(127.5 * (nz / length + 1.0)), 255))
    return (_png_rgba(size, size, colour), _png_rgba(size, size, orm),
            _png_rgba(size, size, normal))


def _write_if_changed(path, data):
    """Write a deterministic generated binary only when its contents changed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_bytes() == data:
        return
    path.write_bytes(data)


def write_gltf(filename, scene_name, materials, mesh_specs, nodes,
               *, external_textures=False):
    """materials: [(name, pbr dict, emissive or None)]; mesh_specs:
    [(mesh name, {material name: Prim})]; nodes reference meshes by name."""
    # Skip catalogue materials that this asset does not actually use. This is
    # especially important for the high-resolution Ne 2 texture set: ordinary
    # signals should not carry three unused 512 px maps in every variant.
    used_materials = {
        material_name
        for _mesh_name, primitives in mesh_specs
        for material_name, primitive in primitives.items()
        if primitive.pos
    }
    materials = [entry for entry in materials if entry[0] in used_materials]
    mat_index = {name: i for i, (name, _, _) in enumerate(materials)}
    blob = bytearray()
    buffer_views, accessors, meshes = [], [], []

    def accessor(data, comp_type, count, type_, target, minmax=None):
        while len(blob) % 4:
            blob.append(0)
        buffer_views.append(
            {"buffer": 0, "byteOffset": len(blob), "byteLength": len(data), "target": target}
        )
        blob.extend(data)
        acc = {
            "bufferView": len(buffer_views) - 1,
            "componentType": comp_type,
            "count": count,
            "type": type_,
        }
        if minmax:
            acc["min"], acc["max"] = minmax
        accessors.append(acc)
        return len(accessors) - 1

    mesh_index = {}
    for mesh_name, prims_by_mat in mesh_specs:
        gl_prims = []
        for mat_name, prim in prims_by_mat.items():
            if not prim.pos:
                continue
            flat_pos = [c for v in prim.pos for c in v]
            flat_nrm = [c for v in prim.nrm for c in v]
            flat_uv = [c for v in prim.uv for c in v]
            mins = [min(p[i] for p in prim.pos) for i in range(3)]
            maxs = [max(p[i] for p in prim.pos) for i in range(3)]
            gl_prims.append(
                {
                    "attributes": {
                        "POSITION": accessor(
                            struct.pack(f"<{len(flat_pos)}f", *flat_pos),
                            5126, len(prim.pos), "VEC3", 34962, (mins, maxs),
                        ),
                        "NORMAL": accessor(
                            struct.pack(f"<{len(flat_nrm)}f", *flat_nrm),
                            5126, len(prim.nrm), "VEC3", 34962,
                        ),
                        "TEXCOORD_0": accessor(
                            struct.pack(f"<{len(flat_uv)}f", *flat_uv),
                            5126, len(prim.uv), "VEC2", 34962,
                        ),
                    },
                    "indices": accessor(
                        struct.pack(f"<{len(prim.idx)}I", *prim.idx),
                        5125, len(prim.idx), "SCALAR", 34963,
                    ),
                    "material": mat_index[mat_name],
                }
            )
        meshes.append({"name": mesh_name, "primitives": gl_prims})
        mesh_index[mesh_name] = len(meshes) - 1

    gl_nodes = []
    for node in nodes:
        out = dict(node)
        if "mesh" in out:
            out["mesh"] = mesh_index[out["mesh"]]
        gl_nodes.append(out)

    gl_materials, images, textures = [], [], []
    sampler = {"magFilter": 9729, "minFilter": 9987, "wrapS": 10497, "wrapT": 10497}
    profile_textures = {}

    def texture_uri(data, generated_name=None):
        if external_textures:
            if not generated_name:
                raise ValueError("external generated textures need a stable name")
            texture_path = SIGNAL_TEXTURES / generated_name
            _write_if_changed(texture_path, data)
            uri = texture_path.relative_to(ASSETS).as_posix()
        else:
            uri = "data:image/png;base64," + base64.b64encode(data).decode()
        images.append({"uri": uri})
        textures.append({"sampler": 0, "source": len(images) - 1})
        return len(textures) - 1

    for name, pbr, emissive in materials:
        pbr = dict(pbr)
        profile = pbr.pop("_texture_profile", None)
        texture_size = pbr.pop("_texture_size", 128)
        glass = pbr.pop("_glass", None)
        clearcoat = pbr.pop("_clearcoat", None)
        mat = {"name": name, "pbrMetallicRoughness": pbr}
        normal_tex = None
        if profile:
            texture_key = (profile, texture_size)
            if texture_key not in profile_textures:
                slug = "".join(
                    character if character.isalnum() else "-"
                    for character in profile.lower()
                ).strip("-")
                profile_textures[texture_key] = tuple(
                    texture_uri(png, f"{slug}-{texture_size}-{kind}.png")
                    for kind, png in zip(
                        ("basecolor", "orm", "normal"),
                        _texture_maps(profile, texture_size),
                    )
                )
            colour_tex, orm_tex, normal_tex = profile_textures[texture_key]
            pbr["baseColorTexture"] = {"index": colour_tex}
            pbr["metallicRoughnessTexture"] = {"index": orm_tex}
            mat["occlusionTexture"] = {"index": orm_tex, "strength": 0.65}
            normal_scale = {
                "optical-glass": 0.01, "led-optical-glass": 0.004,
                "glass": 0.08,
                "enamel": 0.06, "painted": 0.24,
                "black-paint": 0.28, "galvanised": 0.34,
                "ne2-face": 0.22, "rubber": 0.38,
                "rust": 0.78, "concrete": 0.68,
            }.get(profile, 0.28)
            mat["normalTexture"] = {"index": normal_tex, "scale": normal_scale}
        if clearcoat:
            clearcoat_extension = {
                "clearcoatFactor": clearcoat.get("factor", 0.0),
                "clearcoatRoughnessFactor": clearcoat.get("roughness", 0.0),
            }
            if normal_tex is not None and clearcoat.get("normal_scale", 0.0) > 0.0:
                clearcoat_extension["clearcoatNormalTexture"] = {
                    "index": normal_tex,
                    "scale": clearcoat["normal_scale"],
                }
            mat.setdefault("extensions", {})["KHR_materials_clearcoat"] = (
                clearcoat_extension
            )
        if glass:
            mat.setdefault("extensions", {}).update({
                "KHR_materials_transmission": {
                    "transmissionFactor": glass.get("transmission", 0.45),
                },
                "KHR_materials_ior": {"ior": glass.get("ior", 1.52)},
                "KHR_materials_volume": {
                    "thicknessFactor": glass.get("thickness", 0.008),
                    "attenuationDistance": glass.get("attenuation_distance", 0.045),
                    "attenuationColor": glass.get(
                        "attenuation_colour", [1.0, 1.0, 1.0]),
                },
                "KHR_materials_specular": {
                    "specularFactor": glass.get("specular", 1.0),
                },
            })
        if emissive:
            mat["emissiveFactor"] = emissive
        gl_materials.append(mat)

    gltf = {
        "asset": {
            "version": "2.0",
            "generator": "tools/gen_signal_parts.py (Connected Rails example mod)",
            "copyright": COPYRIGHT,
        },
        "scene": 0,
        "scenes": [{"name": scene_name, "nodes": list(range(len(gl_nodes)))}],
        "nodes": gl_nodes,
        "meshes": meshes,
        "materials": gl_materials,
        "accessors": accessors,
        "bufferViews": buffer_views,
        "buffers": [
            {
                "byteLength": len(blob),
                "uri": "data:application/octet-stream;base64,"
                + base64.b64encode(bytes(blob)).decode(),
            }
        ],
    }
    if images:
        gltf["images"] = images
        gltf["samplers"] = [sampler]
        gltf["textures"] = textures
    used_extensions = {
        extension
        for material in gl_materials
        for extension in material.get("extensions", {})
    }
    if used_extensions:
        gltf["extensionsUsed"] = sorted(used_extensions)
    out = ASSETS / filename
    out.write_text(json.dumps(gltf, indent=1) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out} ({out.stat().st_size // 1024} KiB)")


GREY = ("grey", dict(baseColorFactor=[0.42, 0.44, 0.46, 1.0], metallicFactor=0.3, roughnessFactor=0.6), None)
BLACK = ("black", dict(baseColorFactor=[0.03, 0.03, 0.035, 1.0], metallicFactor=0.0, roughnessFactor=0.8), None)
WHITE = ("white", dict(baseColorFactor=[0.85, 0.86, 0.85, 1.0], metallicFactor=0.0, roughnessFactor=0.6), None)
# Lit lenses: emissiveFactor makes them glow without any light of their own.
LENS_RED = ("lens_red", dict(baseColorFactor=[0.8, 0.03, 0.03, 1.0], metallicFactor=0.0, roughnessFactor=0.3), [1.0, 0.05, 0.05])
LENS_GREEN = ("lens_green", dict(baseColorFactor=[0.05, 0.7, 0.2, 1.0], metallicFactor=0.0, roughnessFactor=0.3), [0.1, 1.0, 0.3])
LENS_YELLOW = ("lens_yellow", dict(baseColorFactor=[0.85, 0.6, 0.05, 1.0], metallicFactor=0.0, roughnessFactor=0.3), [1.0, 0.75, 0.1])
LENS_WHITE = ("lens_white", dict(baseColorFactor=[0.9, 0.9, 0.85, 1.0], metallicFactor=0.0, roughnessFactor=0.3), [1.0, 1.0, 0.9])

MAST_H = 3.8
SCHIRM_Y = 3.0  # mp_schirm height on the mast


def build_mast():
    # LOD0: mast with base plate and a small cable box; LOD1: the bare pole.
    lod0 = Prim()
    lod0.box((-0.06, 0.0, -0.06), (0.06, MAST_H, 0.06))
    lod0.box((-0.16, 0.0, -0.16), (0.16, 0.06, 0.16))  # base plate
    lod0.box((-0.10, 0.9, -0.14), (0.10, 1.25, -0.06))  # cable box on the back
    lod1 = Prim()
    lod1.box((-0.06, 0.0, -0.06), (0.06, MAST_H, 0.06))
    write_gltf(
        "sig_mast.gltf",
        "sig_mast",
        [GREY],
        [("mast_LOD0", {"grey": lod0}), ("mast_LOD1", {"grey": lod1})],
        [
            {"name": "mast_LOD0", "mesh": "mast_LOD0"},
            {"name": "mast_LOD1", "mesh": "mast_LOD1"},
            # The screen hangs in front of the mast, facing the driver (+Z).
            {"name": "mp_schirm", "translation": [0.0, SCHIRM_Y, 0.08]},
        ],
    )


# Lamp positions on the Ks screen (x, y): main lamp centre, green above,
# yellow lower left, the two white Zs1 lamps at the bottom.
LAMPS = {
    "lamp_red": ("lens_red", [(0.0, 0.10)]),
    "lamp_green": ("lens_green", [(0.0, 0.34)]),
    "lamp_yellow": ("lens_yellow", [(-0.20, -0.18)]),
    "lamp_zs1": ("lens_white", [(-0.14, -0.40), (0.14, -0.40)]),
}


def build_schirm():
    board = Prim()
    board.box((-0.36, -0.55, 0.0), (0.36, 0.55, 0.06))
    # Dark housings that stay visible while the lens itself is switched off.
    for _, (_, positions) in LAMPS.items():
        for x, y in positions:
            board.box((x - 0.075, y - 0.075, 0.06), (x + 0.075, y + 0.075, 0.085))
    mesh_specs = [("schirm", {"black": board})]
    nodes = [{"name": "schirm", "mesh": "schirm"}]
    for name, (lens, positions) in LAMPS.items():
        prim = Prim()
        for x, y in positions:
            prim.box((x - 0.055, y - 0.055, 0.085), (x + 0.055, y + 0.055, 0.105))
        mesh_specs.append((name, {lens: prim}))
        nodes.append({"name": name, "mesh": name})
    nodes.append({"name": "mp_top", "translation": [0.0, 0.65, 0.0]})
    write_gltf(
        "sig_schirm_ks.gltf",
        "sig_schirm_ks",
        [BLACK, LENS_RED, LENS_GREEN, LENS_YELLOW, LENS_WHITE],
        mesh_specs,
        nodes,
    )


def build_zs3():
    board = Prim()
    board.box((-0.30, 0.0, -0.02), (0.30, 0.72, 0.03))
    # The digit 4 out of three bars, lit white — one node the lamp image toggles.
    digit = Prim()
    digit.box((-0.13, 0.38, 0.03), (-0.08, 0.60, 0.05))  # upper left stroke
    digit.box((-0.13, 0.33, 0.03), (0.13, 0.38, 0.05))   # cross bar
    digit.box((0.08, 0.12, 0.03), (0.13, 0.60, 0.05))    # right stroke
    write_gltf(
        "sig_zs3.gltf",
        "sig_zs3",
        [BLACK, LENS_WHITE],
        [("board", {"black": board}), ("zs3_4", {"lens_white": digit})],
        [
            {"name": "board", "mesh": "board"},
            {"name": "zs3_4", "mesh": "zs3_4"},
        ],
    )


def check():
    # Outward normals on a convex solid — the writer relies on CCW winding.
    prim = Prim()
    prim.box((0, 0, 0), (1, 1, 1))
    for t in range(0, len(prim.idx), 3):
        a, b, c = (prim.pos[prim.idx[t + k]] for k in range(3))
        centroid = tuple((a[i] + b[i] + c[i]) / 3 - 0.5 for i in range(3))
        assert dot(prim.nrm[prim.idx[t]], centroid) > 0, "inward-facing triangle"


if __name__ == "__main__":
    check()
    build_mast()
    build_schirm()
    build_zs3()
