[package]
name = "editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "train-sim-editor"
path = "src/main.rs"

[dependencies]
sim-core = { workspace = true }
track-model = { workspace = true }
world-coords = { workspace = true }
content = { workspace = true }
imagery = { workspace = true }
glam = { workspace = true }
bevy = "0.19"
